version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - haphap-net

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - haphap-net

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle-data:/data
    ports:
      - "127.0.0.1:8888:8080"
    networks:
      - haphap-net

volumes:
  dozzle-data:

networks:
  haphap-net:
    name: haphap-net
    driver: bridge