spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/haphap
    username: haphap
    password: happycats0613!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: happycats0613!happycats0613!happycats0613!