spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/haphap
    username: haphap
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: happycats0613!happycats0613!happycats0613!