spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/haphap
    username: haphap
    password: gmlals02**
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update