global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'haphap-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['haphap-blue:8080', 'haphap-green:8080']
        labels:
          service: 'haphap-server'