CREATE TABLE company_image (
                                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                                updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                                company_id  BIGINT NOT NULL,
                                type        VARCHAR(30) NOT NULL,
                                image_url   VARCHAR(500) NOT NULL,
                                CONSTRAINT uk_company_image_company_type UNIQUE (company_id, type),
                                CONSTRAINT fk_company_image_company FOREIGN KEY (company_id) REFERENCES company (id)
);