-- =====================================================================
-- V11__create_profile_image_table.sql
-- 프로필 이미지 테이블 생성 + 초기 이미지 데이터 일괄 반영
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. profile_image 테이블 생성 + 데이터
-- ---------------------------------------------------------------------
CREATE TABLE profile_image (
                                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                                updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                                image_url   VARCHAR(500) NOT NULL
);

INSERT INTO profile_image (image_url, created_at, updated_at) VALUES
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now());

-- ---------------------------------------------------------------------
-- 2. company_image 데이터 (회사당 5행: POPULAR/LISTING/DETAIL/TODAY_LOGO/CALENDAR_LOGO)
--    회사 id를 몰라도 되게 이름으로 서브쿼리 — 회사명만 정확히 넣으면 됨
-- ---------------------------------------------------------------------
INSERT INTO company_image (company_id, type, image_url, created_at, updated_at) VALUES
((SELECT id FROM company WHERE name = '회사명1'), 'POPULAR', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명1'), 'LISTING', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명1'), 'DETAIL', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명1'), 'TODAY_LOGO', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명1'), 'CALENDAR_LOGO', '', now(), now()),

((SELECT id FROM company WHERE name = '회사명2'), 'POPULAR', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명2'), 'LISTING', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명2'), 'DETAIL', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명2'), 'TODAY_LOGO', '', now(), now()),
((SELECT id FROM company WHERE name = '회사명2'), 'CALENDAR_LOGO', '', now(), now());
-- 회사 수만큼 5행씩 블록 반복

-- ---------------------------------------------------------------------
-- 3. company.card_logo_image_url (합격카드 네모 로고, 회사당 1개)
-- ---------------------------------------------------------------------
UPDATE company SET card_logo_image_url = '' WHERE name = '회사명1';
UPDATE company SET card_logo_image_url = '' WHERE name = '회사명2';
-- 회사 수만큼 반복

-- ---------------------------------------------------------------------
-- 4. category.card_image_url (합격카드 배경, 카테고리당 1개)
-- ---------------------------------------------------------------------
UPDATE category SET card_image_url = '' WHERE name = '카테고리명1';
UPDATE category SET card_image_url = '' WHERE name = '카테고리명2';
-- 카테고리 수만큼 반복

-- ---------------------------------------------------------------------
-- 5. banner (배너 개수만큼)
-- ---------------------------------------------------------------------
INSERT INTO banner (image_url, display_order, is_active, created_at, updated_at) VALUES
('', 1, true, now(), now()),
('', 2, true, now(), now());
-- 배너 개수만큼 반복