CREATE TABLE profile_image (
                                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                                updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                                image_url   VARCHAR(500) NOT NULL
);

INSERT INTO profile_image (image_url, created_at, updated_at) VALUES
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now()),
('', now(), now());