-- =====================================================================
-- V1__init_schema.sql
-- haphap 초기 스키마 (운영 RDS pg_dump --schema-only 기반, 실제 DB와 일치)

-- ---------------------------------------------------------------------
-- 1. users
-- ---------------------------------------------------------------------
CREATE TABLE users (
                       id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at        TIMESTAMP(6) WITHOUT TIME ZONE,
                       updated_at        TIMESTAMP(6) WITHOUT TIME ZONE,
                       anonymous_name    VARCHAR(255) NOT NULL,
                       birth_date        DATE,
                       email             VARCHAR(255),
                       name              VARCHAR(255),
                       provider          VARCHAR(255) NOT NULL,
                       provider_id       VARCHAR(255) NOT NULL,
                       profile_image_url VARCHAR(255),
                       age_range         VARCHAR(255),
                       gender            VARCHAR(255),
                       phone_number      VARCHAR(255),
                       CONSTRAINT ukcbysvpk95086ud4n4g6mkspai UNIQUE (provider, provider_id),
                       CONSTRAINT users_provider_check CHECK ((provider)::text = 'KAKAO'::text)
    );

-- ---------------------------------------------------------------------
-- 2. category
-- ---------------------------------------------------------------------
CREATE TABLE category (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_at     TIMESTAMP(6) WITHOUT TIME ZONE,
                          updated_at     TIMESTAMP(6) WITHOUT TIME ZONE,
                          name           VARCHAR(50) NOT NULL,
                          card_image_url VARCHAR(500)
);

-- ---------------------------------------------------------------------
-- 3. company
-- ---------------------------------------------------------------------
CREATE TABLE company (
                         id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                         updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                         name        VARCHAR(100) NOT NULL,
                         description TEXT,
                         image_url   VARCHAR(255)
);

-- ---------------------------------------------------------------------
-- 4. posting  (category, company 참조)
-- ---------------------------------------------------------------------
CREATE TABLE posting (
                         id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at                 TIMESTAMP(6) WITHOUT TIME ZONE,
                         updated_at                 TIMESTAMP(6) WITHOUT TIME ZONE,
                         deadline                   DATE,
                         expected_announcement_date DATE,
                         title                      VARCHAR(200) NOT NULL,
                         category_id                BIGINT NOT NULL,
                         company_id                 BIGINT NOT NULL,
                         location                   VARCHAR(255),
                         "position"                 VARCHAR(255),
                         CONSTRAINT fke3kj11ixp14wd9fb8ex22pt5o FOREIGN KEY (category_id) REFERENCES category (id),
                         CONSTRAINT fk9oaliwowljjtj71tb5c7jl1sa FOREIGN KEY (company_id)  REFERENCES company (id)
);

CREATE INDEX idx_posting_title ON posting (title);

-- ---------------------------------------------------------------------
-- 5. posting_stage  (posting 참조)  * 감사 컬럼 없음
-- ---------------------------------------------------------------------
CREATE TABLE posting_stage (
                               id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               expected_announcement_date DATE,
                               name                       VARCHAR(50) NOT NULL,
                               order_index                INTEGER NOT NULL,
                               posting_id                 BIGINT NOT NULL,
                               expected_score             INTEGER NOT NULL,
                               announced_date             DATE,
                               CONSTRAINT fk5wq6xmkrmshbvoi5adqbe91j8 FOREIGN KEY (posting_id) REFERENCES posting (id)
);

CREATE INDEX idx_stage_posting_order ON posting_stage (posting_id, order_index);

-- ---------------------------------------------------------------------
-- 6. banner
-- ---------------------------------------------------------------------
CREATE TABLE banner (
                        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
                        updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
                        display_order INTEGER NOT NULL,
                        image_url     VARCHAR(500) NOT NULL,
                        is_active     BOOLEAN NOT NULL
);

CREATE INDEX idx_banner_display_order ON banner (display_order);

-- ---------------------------------------------------------------------
-- 7. alram  (users, posting 참조)
-- ---------------------------------------------------------------------
CREATE TABLE alram (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP(6) WITHOUT TIME ZONE,
                       updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
                       body       VARCHAR(255) NOT NULL,
                       is_read    BOOLEAN NOT NULL,
                       title      VARCHAR(100) NOT NULL,
                       type       VARCHAR(50)  NOT NULL,
                       posting_id BIGINT NOT NULL,
                       user_id    BIGINT NOT NULL,
                       CONSTRAINT alram_type_check CHECK (
                           (type)::text = ANY (ARRAY[
                           'NEW_STAGE_REGISTRATION'::varchar,
                           'STAGE_REGISTERED'::varchar,
                           'DEADLINE'::varchar,
                           'ANNOUNCEMENT'::varchar
                           ]::text[])
),
    CONSTRAINT fkt2xr5n3de1vgqbp3jbhh6itlv FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fkt0wa3thpey9egqwfgadsarki3 FOREIGN KEY (posting_id) REFERENCES posting (id)
);

-- ---------------------------------------------------------------------
-- 8. alram_failure  (FK 제약 없음)
-- ---------------------------------------------------------------------
CREATE TABLE alram_failure (
                               id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               created_at           TIMESTAMP(6) WITHOUT TIME ZONE,
                               updated_at           TIMESTAMP(6) WITHOUT TIME ZONE,
                               failure_message      VARCHAR(1000),
                               failure_type         VARCHAR(100) NOT NULL,
                               posting_id           BIGINT NOT NULL,
                               registrant_member_id BIGINT NOT NULL,
                               resolved             BOOLEAN NOT NULL,
                               stage                VARCHAR(50)
);

-- ---------------------------------------------------------------------
-- 9. alram_setting  (users, posting 참조)
-- ---------------------------------------------------------------------
CREATE TABLE alram_setting (
                               id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               created_at TIMESTAMP(6) WITHOUT TIME ZONE,
                               updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
                               enabled    BOOLEAN NOT NULL,
                               posting_id BIGINT NOT NULL,
                               user_id    BIGINT NOT NULL,
                               CONSTRAINT uk_alram_setting_member_posting UNIQUE (user_id, posting_id),
                               CONSTRAINT fkgmb9ob76xmwj5q7wi5drjw19c FOREIGN KEY (user_id)    REFERENCES users (id),
                               CONSTRAINT fki90g0qer9sn5bin8im9cut86b FOREIGN KEY (posting_id) REFERENCES posting (id)
);

-- ---------------------------------------------------------------------
-- 10. push_token  (users 참조)
-- ---------------------------------------------------------------------
CREATE TABLE push_token (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                            updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
                            active      BOOLEAN NOT NULL,
                            device_type VARCHAR(20),
                            fcm_token   VARCHAR(255) NOT NULL,
                            user_id     BIGINT NOT NULL,
                            device_id   VARCHAR(255) NOT NULL,
                            CONSTRAINT push_token_device_type_check CHECK (
                                (device_type)::text = ANY (ARRAY[
                                'ANDROID'::varchar,
                                'IOS'::varchar,
                                'WEB'::varchar
                                ]::text[])
),
    CONSTRAINT uk_push_token_user_device UNIQUE (user_id, device_id),
    CONSTRAINT fkek7gbm3fy30fop64qimiy7vja FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------
-- 11. stage_result_count  (FK 제약 없음)
-- ---------------------------------------------------------------------
CREATE TABLE stage_result_count (
                                    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    fail_count    BIGINT NOT NULL,
                                    pass_count    BIGINT NOT NULL,
                                    pending_count BIGINT NOT NULL,
                                    posting_id    BIGINT NOT NULL,
                                    stage_id      BIGINT NOT NULL,
                                    CONSTRAINT uk_stage_result_count UNIQUE (posting_id, stage_id)
);

-- ---------------------------------------------------------------------
-- 12. registration  (users, posting, posting_stage 참조)
--     ※ stage(varchar) 컬럼은 실제 DB 에 존재하여 포함 (엔티티엔 없음)
-- ---------------------------------------------------------------------
CREATE TABLE registration (
                              id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              created_at     TIMESTAMP(6) WITHOUT TIME ZONE,
                              updated_at     TIMESTAMP(6) WITHOUT TIME ZONE,
                              anonymous      BOOLEAN NOT NULL,
                              contact_method VARCHAR(20),
                              contacted_at   DATE,
                              result         VARCHAR(20) NOT NULL,
                              stage          VARCHAR(50) NOT NULL,
                              posting_id     BIGINT NOT NULL,
                              user_id        BIGINT NOT NULL,
                              stage_id       BIGINT NOT NULL,
                              CONSTRAINT registration_result_check CHECK (
                                  (result)::text = ANY (ARRAY[
                                  'PASS'::varchar,
                                  'FAIL'::varchar,
                                  'PENDING'::varchar
                                  ]::text[])
),
    CONSTRAINT registration_contact_method_check CHECK (
        (contact_method)::text = ANY (ARRAY[
            'EMAIL'::varchar,
            'SMS'::varchar,
            'PHONE_CALL'::varchar,
            'KAKAO'::varchar,
            'ETC'::varchar
        ]::text[])
    ),
    CONSTRAINT uk_registration_user_posting_stage UNIQUE (user_id, posting_id, stage_id),
    CONSTRAINT fkkyuphiynxwt1mtlfsptc991sc FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk8a0i5lf5bu8ydhxn8qytlv6os FOREIGN KEY (posting_id) REFERENCES posting (id),
    CONSTRAINT fk8p81nhfr3yrmgttqb1w5bsvu8 FOREIGN KEY (stage_id)   REFERENCES posting_stage (id)
);

CREATE INDEX idx_reg_posting_stage  ON registration (posting_id, stage_id);
CREATE INDEX idx_reg_result_updated ON registration (result, updated_at);