INSERT INTO related_search_keyword (keyword, is_active, created_at, updated_at)
VALUES
    ('카카오', true, NOW(), NOW()),
    ('주식회사 카카오', true, NOW(), NOW()),
    ('㈜카카오', true, NOW(), NOW()),
    ('kakao', true, NOW(), NOW()),
    ('KAKAO', true, NOW(), NOW()),
    ('카카오 채용', true, NOW(), NOW()),
    ('카카오 신입', true, NOW(), NOW()),
    ('카카오 인턴', true, NOW(), NOW()),
    ('카카오 공채', true, NOW(), NOW()),
    ('카카오 크루', true, NOW(), NOW()),
    ('판교 카카오', true, NOW(), NOW()),
    ('카카오 본사', true, NOW(), NOW()),
    ('카카오톡', true, NOW(), NOW()),
    ('다음카카오', true, NOW(), NOW()),
    ('daum kakao', true, NOW(), NOW()),
    ('네이버', true, NOW(), NOW()),
    ('주식회사 네이버', true, NOW(), NOW()),
    ('㈜네이버', true, NOW(), NOW()),
    ('NAVER', true, NOW(), NOW()),
    ('naver', true, NOW(), NOW()),
    ('네이버 채용', true, NOW(), NOW()),
    ('네이버 신입', true, NOW(), NOW()),
    ('네이버 인턴', true, NOW(), NOW()),
    ('네이버 공채', true, NOW(), NOW()),
    ('네이버 커넥트', true, NOW(), NOW()),
    ('네이버랩스', true, NOW(), NOW()),
    ('네이버웹툰', true, NOW(), NOW()),
    ('네이버클라우드', true, NOW(), NOW()),
    ('라인플러스', true, NOW(), NOW()),
    ('분당 네이버', true, NOW(), NOW()),
    ('토스', true, NOW(), NOW()),
    ('비바리퍼블리카', true, NOW(), NOW()),
    ('주식회사 비바리퍼블리카', true, NOW(), NOW()),
    ('Toss', true, NOW(), NOW()),
    ('toss', true, NOW(), NOW()),
    ('Viva Republica', true, NOW(), NOW()),
    ('토스 채용', true, NOW(), NOW()),
    ('토스 신입', true, NOW(), NOW()),
    ('토스 인턴', true, NOW(), NOW()),
    ('토스 공채', true, NOW(), NOW()),
    ('토스팀', true, NOW(), NOW()),
    ('토스 커뮤니티', true, NOW(), NOW()),
    ('토스뱅크', true, NOW(), NOW()),
    ('토스증권', true, NOW(), NOW()),
    ('토스페이먼츠', true, NOW(), NOW()),
    ('LG생활건강', true, NOW(), NOW()),
    ('엘지생활건강', true, NOW(), NOW()),
    ('LG 생활건강', true, NOW(), NOW()),
    ('엘지 생활건강', true, NOW(), NOW()),
    ('LG H&H', true, NOW(), NOW()),
    ('LG HNH', true, NOW(), NOW()),
    ('LG Household & Health Care', true, NOW(), NOW()),
    ('생활건강', true, NOW(), NOW()),
    ('엘생', true, NOW(), NOW()),
    ('LG생활건강 채용', true, NOW(), NOW()),
    ('LG생활건강 신입', true, NOW(), NOW()),
    ('LG생활건강 인턴', true, NOW(), NOW()),
    ('LG생활건강 공채', true, NOW(), NOW()),
    ('더후', true, NOW(), NOW()),
    ('오휘', true, NOW(), NOW()),
    ('피지오겔', true, NOW(), NOW()),
    ('현대자동차', true, NOW(), NOW()),
    ('현대차', true, NOW(), NOW()),
    ('현차', true, NOW(), NOW()),
    ('현대 자동차', true, NOW(), NOW()),
    ('HYUNDAI', true, NOW(), NOW()),
    ('Hyundai Motor', true, NOW(), NOW()),
    ('Hyundai Motor Company', true, NOW(), NOW()),
    ('HMC', true, NOW(), NOW()),
    ('현대자동차 채용', true, NOW(), NOW()),
    ('현대차 채용', true, NOW(), NOW()),
    ('현대자동차 신입', true, NOW(), NOW()),
    ('현대차 신입', true, NOW(), NOW()),
    ('현대자동차 인턴', true, NOW(), NOW()),
    ('현대자동차 공채', true, NOW(), NOW()),
    ('양재 현대차', true, NOW(), NOW()),
    ('남양연구소', true, NOW(), NOW()),
    ('아모레퍼시픽', true, NOW(), NOW()),
    ('아모레 퍼시픽', true, NOW(), NOW()),
    ('아모레', true, NOW(), NOW()),
    ('AMOREPACIFIC', true, NOW(), NOW()),
    ('Amore Pacific', true, NOW(), NOW()),
    ('아모레퍼시픽그룹', true, NOW(), NOW()),
    ('아모레퍼시픽 채용', true, NOW(), NOW()),
    ('아모레 채용', true, NOW(), NOW()),
    ('아모레퍼시픽 신입', true, NOW(), NOW()),
    ('아모레퍼시픽 인턴', true, NOW(), NOW()),
    ('아모레퍼시픽 공채', true, NOW(), NOW()),
    ('설화수', true, NOW(), NOW()),
    ('라네즈', true, NOW(), NOW()),
    ('이니스프리', true, NOW(), NOW()),
    ('에뛰드', true, NOW(), NOW()),
    ('헤라', true, NOW(), NOW()),
    ('카카오페이', true, NOW(), NOW()),
    ('카카오스타일', true, NOW(), NOW()),
    ('kakaopay', true, NOW(), NOW()),
    ('Kakao Pay', true, NOW(), NOW()),
    ('KAKAO PAY', true, NOW(), NOW()),
    ('카페이', true, NOW(), NOW()),
    ('카카오페이 채용', true, NOW(), NOW()),
    ('카카오페이 신입', true, NOW(), NOW()),
    ('카카오페이 인턴', true, NOW(), NOW()),
    ('카카오페이 공채', true, NOW(), NOW()),
    ('카카오페이 크루', true, NOW(), NOW()),
    ('카카오페이 경력', true, NOW(), NOW()),
    ('카카오페이 결제', true, NOW(), NOW()),
    ('카카오페이 금융', true, NOW(), NOW()),
    ('판교 카카오페이', true, NOW(), NOW()),
    ('카카오뱅크', true, NOW(), NOW()),
    ('카카오페이증권', true, NOW(), NOW()),
    ('카뱅', true, NOW(), NOW()),
    ('kakaobank', true, NOW(), NOW()),
    ('KakaoBank', true, NOW(), NOW()),
    ('KAKAO BANK', true, NOW(), NOW()),
    ('한국카카오은행', true, NOW(), NOW()),
    ('카카오뱅크 채용', true, NOW(), NOW()),
    ('카뱅 채용', true, NOW(), NOW()),
    ('카카오뱅크 신입', true, NOW(), NOW()),
    ('카카오뱅크 인턴', true, NOW(), NOW()),
    ('카카오뱅크 공채', true, NOW(), NOW()),
    ('카카오뱅크 경력', true, NOW(), NOW()),
    ('인터넷은행', true, NOW(), NOW()),
    ('판교 카카오뱅크', true, NOW(), NOW()),
    ('카카오 스타일', true, NOW(), NOW()),
    ('kakaostyle', true, NOW(), NOW()),
    ('Kakao Style', true, NOW(), NOW()),
    ('KAKAO STYLE', true, NOW(), NOW()),
    ('지그재그', true, NOW(), NOW()),
    ('zigzag', true, NOW(), NOW()),
    ('카카오스타일 채용', true, NOW(), NOW()),
    ('카카오스타일 신입', true, NOW(), NOW()),
    ('카카오스타일 인턴', true, NOW(), NOW()),
    ('카카오스타일 공채', true, NOW(), NOW()),
    ('카카오스타일 경력', true, NOW(), NOW()),
    ('지그재그 채용', true, NOW(), NOW()),
    ('패션 플랫폼', true, NOW(), NOW()),
    ('크로키닷컴', true, NOW(), NOW()),
    ('카카오페이 증권', true, NOW(), NOW()),
    ('카페증', true, NOW(), NOW()),
    ('kakaopay securities', true, NOW(), NOW()),
    ('Kakao Pay Securities', true, NOW(), NOW()),
    ('카카오페이증권 채용', true, NOW(), NOW()),
    ('카카오페이증권 신입', true, NOW(), NOW()),
    ('카카오페이증권 인턴', true, NOW(), NOW()),
    ('카카오페이증권 공채', true, NOW(), NOW()),
    ('카카오페이증권 경력', true, NOW(), NOW()),
    ('카카오페이 주식', true, NOW(), NOW()),
    ('카카오페이 투자', true, NOW(), NOW()),
    ('카카오 증권', true, NOW(), NOW()),
    ('바로투자증권', true, NOW(), NOW()),
    ('핀테크 증권사', true, NOW(), NOW())
ON CONFLICT (keyword) DO NOTHING;