-- 운영진 검토 대상 큐. 불합격 결과 중 자동으로 판단하기 어려운 두 가지(하루 내 2건 이상 / 후속 전형)를
-- 여기 쌓아두고, 운영진이 승인(ACCEPTED)하기 전까지 집계(StageResultCount)에는 반영하지 않는다.
CREATE TABLE registration_review (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    registration_id BIGINT NOT NULL,
    reason          VARCHAR(30) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    CONSTRAINT fk_review_registration FOREIGN KEY (registration_id) REFERENCES registration (id)
);

CREATE INDEX idx_review_status ON registration_review (status);
