-- 홈 [최근 조회한 공고]: 유저별 공고 조회 이력. (user_id, posting_id)당 1row로 upsert하고
-- last_viewed_at만 갱신한다. 30일 지난 건 조회 시점에 필터링만 하고 row는 지우지 않는다
-- ("비식별 데이터로써 접속 기록 자체는 유지").
CREATE TABLE posting_view_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    user_id         BIGINT NOT NULL,
    posting_id      BIGINT NOT NULL,
    last_viewed_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_posting_view_history UNIQUE (user_id, posting_id),
    CONSTRAINT fk_view_history_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_view_history_posting FOREIGN KEY (posting_id) REFERENCES posting (id)
);

CREATE INDEX idx_view_history_user_last_viewed ON posting_view_history (user_id, last_viewed_at);
