-- 합격 인증 이미지. 업로드 시점에는 registration_id가 NULL이고, 결과 등록 시 연결됩니다
CREATE TABLE verification_image (
                                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
                                    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE,
                                    user_id         BIGINT       NOT NULL,
                                    registration_id BIGINT,
                                    s3_key          VARCHAR(255) NOT NULL UNIQUE,
                                    sort_order      INT,
                                    CONSTRAINT fk_verification_image_user         FOREIGN KEY (user_id)         REFERENCES users (id),
                                    CONSTRAINT fk_verification_image_registration FOREIGN KEY (registration_id) REFERENCES registration (id)
);
CREATE INDEX idx_verification_image_registration ON verification_image (registration_id);
CREATE INDEX idx_verification_image_orphan ON verification_image (created_at) WHERE registration_id IS NULL;